### ISSUE TITLE
Which Durus do I use?

### ISSUE THREAD

**Issue by clozinski** [nascheme/durus#3]
Hello.
I am very glad to see that Durus has been moved to Github in Febuary of this year.  It means that it is alive.  

I am a user of ZODB for many many years, but I am thinking of migrating to Durus.  Much simpler and easier to modify.   I run blogory.org/durus, the world's largest Durus directory, part of the world's largest Python directory. 

So a couple of questions.  Is this now the authoritative version of Durus?  

Can we mention that 
https://bitbucket.org/pombredanne/durus
is no longer authoritative.  Do you know that person?
Could we do the same on bitbucket?

So is anyone actively using Durus?  

Is there a mailing list?  Could we start one?

Chris

**Comment by nascheme** [comment]
Hi,
As far as I'm aware, MEMS Exchange is still maintaining Durus as a component of their DurusWorks package.  I want to use Durus as a separate package so I have been maintaining this github repo that only contains Durus.  There are very minimal difference between the MEMS Exchange version and this version.  In this version I have restored the "FileStorage" backend layer as it has some different performance tradeoffs (slower startup time, more RAM use, faster object loading).

I was not aware of the https://bitbucket.org/pombredanne/durus repository.  It looks like there are some useful modifications there that could be merged into this github repo.

I'm not sure if the durus-users@mems-exchange.org list is still active.  Sending an email to rmasse <at> mems-exchange.org might get a response.

**Comment by clozinski** [comment]
So I updated

blogory.org/durus

I created a mailing list on Google Groups.  You can find the link above.

I linked to your github repository.  Link is also above.  I invite you
to proofread what I said.

Was the MEMS version running on SQL Lite before you moved to FileStorage?

I invite you to write a blog posting on why you chose Durus instead of
the more heavily used ZODB.

Just register on the site, I will give you permission to add content.

Id you approve what I have done, I will go ahead and announce this page on

reddit.com and maybe on Awesome Python. 

More users is presumably a good thing.

Where does my interest lie?  Well blogory is written on ZODB, but ZODB
just keeps getting larger and larger.

I like the simple is better model.

https://www.simple-is-better.org/

The less lines of code the easier it is to do something.

In particular I am interested in doing a real time web server with
Persistent Python Objects.  Modifying ZODB with 2000 lines of code in
File storage will be way harder than making Durus do my bidding.

Regards

Chris

**Comment by clozinski** [comment]
And I updated the home page.

blogory.org/durus

Please let me know if I correctly represented the Durus database.

Chris

**Comment by nascheme** [comment]
Looks basically okay. There are people using Durus for large applications.  We have a multi-gigabyte database that is used for an app that has hundreds of paying users.
